[project]
name = "testing-django-websocket"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "channels>=4.2.0",
    "daphne>=4.1.2",
    "django>=5.1.6",
]
